AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 20

Resources:
  loadData:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: code/
      Handler: app.wheather
      Runtime: python3.8
